# ST Variants pack – variant character definitions only.
# Design and structure match characters_ST; message is blank; fallback to ST message at runtime via default_character.
# Do not add base_folder, age_teen_folder, or age_adult_folder. One pack reads the other.

## Pack link (separate section)
# This pack links to the ST pack. Variant entries use default_character (e.g. characters_ST/abby) to identify
# the base character; when message is blank, the loader uses the ST message for that character.
# ST pack must be present and enabled for this pack to function.

import os

# Bot name from environment, defaults to "Syn" for backwards compatibility
BOT_NAME = os.getenv("TFBOT_NAME", "Syn").strip() or "Syn"

# Helper function to replace bot name placeholder in messages
def _format_message(message: str) -> str:
    """Replace {BOT_NAME} placeholder with actual bot name."""
    return message.replace("{BOT_NAME}", BOT_NAME)

# One block per base character; variants inherit default_character from the block.
CHARACTER_BLOCKS = [
    # Abby
    {
        "default_character": 'characters_ST/abby',
        "variants": [
            {
                "name": 'AbbyAR',
                "gender": 'female',
                "genderswap": 'variants_abbygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_abbyar',
                "message": '',
                "ageswap": 'characters_ST/abby',
                "gender_age_swap": 'variants_abbygb',
            },
            {
                "name": 'AbbyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/abby',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_abbygb',
                "message": '',
                "ageswap": 'variants_abbygbar',
                "gender_age_swap": 'variants_abbyar',
            },
            {
                "name": 'AbbyGBAR',
                "gender": 'male',
                "genderswap": 'variants_abbyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_abbygbar',
                "message": '',
                "ageswap": 'variants_abbygb',
                "gender_age_swap": 'characters_ST/abby',
            },
        ],
    },

    # Alex
    {
        "default_character": 'characters_ST/alex',
        "variants": [
            {
                "name": 'AlexAR',
                "gender": 'female',
                "genderswap": 'variants_alexgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_alexar',
                "message": '',
                "ageswap": 'characters_ST/alex',
                "gender_age_swap": 'variants_alexgb',
            },
            {
                "name": 'AlexGB',
                "gender": 'male',
                "genderswap": 'characters_ST/alex',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_alexgb',
                "message": '',
                "ageswap": 'variants_alexgbar',
                "gender_age_swap": 'variants_alexar',
            },
            {
                "name": 'AlexGBAR',
                "gender": 'male',
                "genderswap": 'variants_alexar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_alexgbar',
                "message": '',
                "ageswap": 'variants_alexgb',
                "gender_age_swap": 'characters_ST/alex',
            },
        ],
    },

    # Allison
    {
        "default_character": 'characters_ST/allison',
        "variants": [
            {
                "name": 'AllisonAP',
                "gender": 'female',
                "genderswap": 'variants_allisongbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_allisonap',
                "message": '',
                "ageswap": 'characters_ST/allison',
                "gender_age_swap": 'variants_allisongb',
            },
            {
                "name": 'AllisonGB',
                "gender": 'male',
                "genderswap": 'characters_ST/allison',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_allisongb',
                "message": '',
                "ageswap": 'variants_allisongbap',
                "gender_age_swap": 'variants_allisonap',
            },
            {
                "name": 'AllisonGBAP',
                "gender": 'male',
                "genderswap": 'variants_allisonap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_allisongbap',
                "message": '',
                "ageswap": 'variants_allisongb',
                "gender_age_swap": 'characters_ST/allison',
            },
        ],
    },

    # Amy
    {
        "default_character": 'characters_ST/amy',
        "variants": [
            {
                "name": 'AmyAP',
                "gender": 'female',
                "genderswap": 'variants_amygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_amyap',
                "message": '',
                "ageswap": 'characters_ST/amy',
                "gender_age_swap": 'variants_amygb',
            },
            {
                "name": 'AmyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/amy',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_amygb',
                "message": '',
                "ageswap": 'variants_amygbap',
                "gender_age_swap": 'variants_amyap',
            },
            {
                "name": 'AmyGBAP',
                "gender": 'male',
                "genderswap": 'variants_amyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_amygbap',
                "message": '',
                "ageswap": 'variants_amygb',
                "gender_age_swap": 'characters_ST/amy',
            },
        ],
    },

    # Anuja
    {
        "default_character": 'characters_ST/anuja',
        "variants": [
            {
                "name": 'AnujaAP',
                "gender": 'female',
                "genderswap": 'variants_anujagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_anujaap',
                "message": '',
                "ageswap": 'characters_ST/anuja',
                "gender_age_swap": 'variants_anujagb',
            },
            {
                "name": 'AnujaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/anuja',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_anujagb',
                "message": '',
                "ageswap": 'variants_anujagbap',
                "gender_age_swap": 'variants_anujaap',
            },
            {
                "name": 'AnujaGBAP',
                "gender": 'male',
                "genderswap": 'variants_anujaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_anujagbap',
                "message": '',
                "ageswap": 'variants_anujagb',
                "gender_age_swap": 'characters_ST/anuja',
            },
        ],
    },

    # Audrey
    {
        "default_character": 'characters_ST/audrey',
        "variants": [
            {
                "name": 'AudreyAP',
                "gender": 'female',
                "genderswap": 'variants_audreygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_audreyap',
                "message": '',
                "ageswap": 'characters_ST/audrey',
                "gender_age_swap": 'variants_audreygb',
            },
            {
                "name": 'AudreyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/audrey',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_audreygb',
                "message": '',
                "ageswap": 'variants_audreygbap',
                "gender_age_swap": 'variants_audreyap',
            },
            {
                "name": 'AudreyGBAP',
                "gender": 'male',
                "genderswap": 'variants_audreyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_audreygbap',
                "message": '',
                "ageswap": 'variants_audreygb',
                "gender_age_swap": 'characters_ST/audrey',
            },
        ],
    },

    # Brad
    {
        "default_character": 'characters_ST/brad',
        "variants": [
            {
                "name": 'BradAP',
                "gender": 'male',
                "genderswap": 'variants_bradgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_bradap',
                "message": '',
                "ageswap": 'characters_ST/brad',
                "gender_age_swap": 'characters_ST/bradGB',
            },
            {
                "name": 'BradGBAP',
                "gender": 'female',
                "genderswap": 'variants_bradap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_bradgbap',
                "message": '',
                "ageswap": 'characters_ST/bradGB',
                "gender_age_swap": 'characters_ST/brad',
            },
        ],
    },

    # Carla
    {
        "default_character": 'characters_ST/carla',
        "variants": [
            {
                "name": 'CarlaAR',
                "gender": 'female',
                "genderswap": 'variants_carlagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carlaar',
                "message": '',
                "ageswap": 'characters_ST/carla',
                "gender_age_swap": 'variants_carlagb',
            },
            {
                "name": 'CarlaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/carla',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carlagb',
                "message": '',
                "ageswap": 'variants_carlagbar',
                "gender_age_swap": 'variants_carlaar',
            },
            {
                "name": 'CarlaGBAR',
                "gender": 'male',
                "genderswap": 'variants_carlaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carlagbar',
                "message": '',
                "ageswap": 'variants_carlagb',
                "gender_age_swap": 'characters_ST/carla',
            },
        ],
    },

    # Carrie
    {
        "default_character": 'characters_ST/carrie',
        "variants": [
            {
                "name": 'CarrieAP',
                "gender": 'female',
                "genderswap": 'variants_carriegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carrieap',
                "message": '',
                "ageswap": 'characters_ST/carrie',
                "gender_age_swap": 'variants_carriegb',
            },
            {
                "name": 'CarrieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/carrie',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carriegb',
                "message": '',
                "ageswap": 'variants_carriegbap',
                "gender_age_swap": 'variants_carrieap',
            },
            {
                "name": 'CarrieGBAP',
                "gender": 'male',
                "genderswap": 'variants_carrieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_carriegbap',
                "message": '',
                "ageswap": 'variants_carriegb',
                "gender_age_swap": 'characters_ST/carrie',
            },
        ],
    },

    # Casey
    {
        "default_character": 'characters_ST/casey',
        "variants": [
            {
                "name": 'CaseyAP',
                "gender": 'female',
                "genderswap": 'variants_caseygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_caseyap',
                "message": '',
                "ageswap": 'characters_ST/casey',
                "gender_age_swap": 'variants_caseygb',
            },
            {
                "name": 'CaseyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/casey',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_caseygb',
                "message": '',
                "ageswap": 'variants_caseygbap',
                "gender_age_swap": 'variants_caseyap',
            },
            {
                "name": 'CaseyGBAP',
                "gender": 'male',
                "genderswap": 'variants_caseyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_caseygbap',
                "message": '',
                "ageswap": 'variants_caseygb',
                "gender_age_swap": 'characters_ST/casey',
            },
        ],
    },

    # Cassie
    {
        "default_character": 'characters_ST/cassie',
        "variants": [
            {
                "name": 'CassieAR',
                "gender": 'female',
                "genderswap": 'variants_cassiegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_cassiear',
                "message": '',
                "ageswap": 'characters_ST/cassie',
                "gender_age_swap": 'variants_cassiegb',
            },
            {
                "name": 'CassieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/cassie',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_cassiegb',
                "message": '',
                "ageswap": 'variants_cassiegbar',
                "gender_age_swap": 'variants_cassiear',
            },
            {
                "name": 'CassieGBAR',
                "gender": 'male',
                "genderswap": 'variants_cassiear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_cassiegbar',
                "message": '',
                "ageswap": 'variants_cassiegb',
                "gender_age_swap": 'characters_ST/cassie',
            },
        ],
    },

    # Charlotte
    {
        "default_character": 'characters_ST/charlotte',
        "variants": [
            {
                "name": 'CharlotteAR',
                "gender": 'female',
                "genderswap": 'variants_charlottegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_charlottear',
                "message": '',
                "ageswap": 'characters_ST/charlotte',
                "gender_age_swap": 'variants_charlottegb',
            },
            {
                "name": 'CharlotteGB',
                "gender": 'male',
                "genderswap": 'characters_ST/charlotte',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_charlottegb',
                "message": '',
                "ageswap": 'variants_charlottegbar',
                "gender_age_swap": 'variants_charlottear',
            },
            {
                "name": 'CharlotteGBAR',
                "gender": 'male',
                "genderswap": 'variants_charlottear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_charlottegbar',
                "message": '',
                "ageswap": 'variants_charlottegb',
                "gender_age_swap": 'characters_ST/charlotte',
            },
        ],
    },

    # Circe
    {
        "default_character": 'characters_ST/circe',
        "variants": [
            {
                "name": 'CirceGB',
                "gender": 'male',
                "genderswap": 'characters_ST/circe',
                "age": 'adult',
                "type": 'demon',
                "avatar_path": None,
                "folder": 'variants_circeGB',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/circe',
            },
        ],
    },

    # Claus
    {
        "default_character": 'characters_ST/claus',
        "variants": [
            {
                "name": 'ClausAP',
                "gender": 'male',
                "genderswap": 'variants_clausgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_clausap',
                "message": '',
                "ageswap": 'characters_ST/claus',
                "gender_age_swap": 'variants_clausgb',
            },
            {
                "name": 'ClausGB',
                "gender": 'female',
                "genderswap": 'characters_ST/claus',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_clausgb',
                "message": '',
                "ageswap": 'variants_clausgbap',
                "gender_age_swap": 'variants_clausap',
            },
            {
                "name": 'ClausGBAP',
                "gender": 'female',
                "genderswap": 'variants_clausap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_clausgbap',
                "message": '',
                "ageswap": 'variants_clausgb',
                "gender_age_swap": 'characters_ST/claus',
            },
        ],
    },

    # Connie
    {
        "default_character": 'characters_ST/connie',
        "variants": [
            {
                "name": 'ConnieAR',
                "gender": 'female',
                "genderswap": 'variants_conniegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_conniear',
                "message": '',
                "ageswap": 'characters_ST/connie',
                "gender_age_swap": 'variants_conniegb',
            },
            {
                "name": 'ConnieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/connie',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_conniegb',
                "message": '',
                "ageswap": 'variants_conniegbar',
                "gender_age_swap": 'variants_conniear',
            },
            {
                "name": 'ConnieGBAR',
                "gender": 'male',
                "genderswap": 'variants_conniear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_conniegbar',
                "message": '',
                "ageswap": 'variants_conniegb',
                "gender_age_swap": 'characters_ST/connie',
            },
        ],
    },

    # Cornelia
    {
        "default_character": 'characters_ST/cornelia',
        "variants": [
            {
                "name": 'CorneliaAP',
                "gender": 'female',
                "genderswap": 'variants_corneliagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_corneliaap',
                "message": '',
                "ageswap": 'characters_ST/cornelia',
                "gender_age_swap": 'characters_Shorts/corneliaGB_shorts',
            },
            {
                "name": 'CorneliaGBAP',
                "gender": 'male',
                "genderswap": 'variants_corneliaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_corneliagbap',
                "message": '',
                "ageswap": 'characters_Shorts/corneliaGB_shorts',
                "gender_age_swap": 'characters_ST/cornelia',
            },
        ],
    },

    # Dominic
    {
        "default_character": 'characters_ST/dominic',
        "variants": [
            {
                "name": 'DominicAR',
                "gender": 'male',
                "genderswap": 'variants_dominicgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_dominicar',
                "message": '',
                "ageswap": 'characters_ST/dominic',
                "gender_age_swap": 'variants_dominicgb',
            },
            {
                "name": 'DominicGB',
                "gender": 'female',
                "genderswap": 'characters_ST/dominic',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_dominicgb',
                "message": '',
                "ageswap": 'variants_dominicgbar',
                "gender_age_swap": 'variants_dominicar',
            },
            {
                "name": 'DominicGBAR',
                "gender": 'female',
                "genderswap": 'variants_dominicar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_dominicgbar',
                "message": '',
                "ageswap": 'variants_dominicgb',
                "gender_age_swap": 'characters_ST/dominic',
            },
        ],
    },

    # Donna
    {
        "default_character": 'characters_ST/donna',
        "variants": [
            {
                "name": 'DonnaAR',
                "gender": 'female',
                "genderswap": 'variants_donnagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_donnaar',
                "message": '',
                "ageswap": 'characters_ST/donna',
                "gender_age_swap": 'variants_donnagb',
            },
            {
                "name": 'DonnaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/donna',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_donnagb',
                "message": '',
                "ageswap": 'variants_donnagbar',
                "gender_age_swap": 'variants_donnaar',
            },
            {
                "name": 'DonnaGBAR',
                "gender": 'male',
                "genderswap": 'variants_donnaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_donnagbar',
                "message": '',
                "ageswap": 'variants_donnagb',
                "gender_age_swap": 'characters_ST/donna',
            },
        ],
    },

    # Elizabeth
    {
        "default_character": 'characters_ST/elizabeth',
        "variants": [
            {
                "name": 'ElizabethAR',
                "gender": 'female',
                "genderswap": 'variants_elizabethgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_elizabethar',
                "message": '',
                "ageswap": 'characters_ST/elizabeth',
                "gender_age_swap": 'variants_elizabethgb',
            },
            {
                "name": 'ElizabethGB',
                "gender": 'male',
                "genderswap": 'characters_ST/elizabeth',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_elizabethgb',
                "message": '',
                "ageswap": 'variants_elizabethgbar',
                "gender_age_swap": 'variants_elizabethar',
            },
            {
                "name": 'ElizabethGBAR',
                "gender": 'male',
                "genderswap": 'variants_elizabethar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_elizabethgbar',
                "message": '',
                "ageswap": 'variants_elizabethgb',
                "gender_age_swap": 'characters_ST/elizabeth',
            },
        ],
    },

    # Emily
    {
        "default_character": 'characters_ST/emily',
        "variants": [
            {
                "name": 'EmilyAP',
                "gender": 'female',
                "genderswap": 'variants_emilygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_emilyap',
                "message": '',
                "ageswap": 'characters_ST/emily',
                "gender_age_swap": 'variants_emilygb',
            },
            {
                "name": 'EmilyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/emily',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_emilygb',
                "message": '',
                "ageswap": 'variants_emilygbap',
                "gender_age_swap": 'variants_emilyap',
            },
            {
                "name": 'EmilyGBAP',
                "gender": 'male',
                "genderswap": 'variants_emilyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_emilygbap',
                "message": '',
                "ageswap": 'variants_emilygb',
                "gender_age_swap": 'characters_ST/emily',
            },
        ],
    },

    # Eric
    {
        "default_character": 'characters_ST/eric',
        "variants": [
            {
                "name": 'EricAP',
                "gender": 'male',
                "genderswap": 'variants_ericgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ericap',
                "message": '',
                "ageswap": 'characters_ST/eric',
                "gender_age_swap": 'characters_ST/ericGB',
            },
            {
                "name": 'EricGBAP',
                "gender": 'female',
                "genderswap": 'variants_ericap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ericgbap',
                "message": '',
                "ageswap": 'characters_ST/ericGB',
                "gender_age_swap": 'characters_ST/eric',
            },
        ],
    },

    # Flavia
    {
        "default_character": 'characters_ST/flavia',
        "variants": [
            {
                "name": 'FlaviaAP',
                "gender": 'female',
                "genderswap": 'variants_flaviagbar',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_flaviaap',
                "message": '',
                "ageswap": 'characters_ST/flavia',
                "gender_age_swap": 'variants_flaviagb',
            },
            {
                "name": 'FlaviaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/flavia',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_flaviagb',
                "message": '',
                "ageswap": 'variants_flaviagbar',
                "gender_age_swap": 'variants_flaviaap',
            },
            {
                "name": 'FlaviaGBAR',
                "gender": 'male',
                "genderswap": 'variants_flaviaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_flaviagbar',
                "message": '',
                "ageswap": 'variants_flaviagb',
                "gender_age_swap": 'characters_ST/flavia',
            },
        ],
    },

    # Gabriel
    {
        "default_character": 'characters_ST/gabriel',
        "variants": [
            {
                "name": 'GabrielAP',
                "gender": 'male',
                "genderswap": 'variants_gabrielgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gabrielap',
                "message": '',
                "ageswap": 'characters_ST/gabriel',
                "gender_age_swap": 'variants_gabrielgb',
            },
            {
                "name": 'GabrielGB',
                "gender": 'female',
                "genderswap": 'characters_ST/gabriel',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gabrielgb',
                "message": '',
                "ageswap": 'variants_gabrielgbap',
                "gender_age_swap": 'variants_gabrielap',
            },
            {
                "name": 'GabrielGBAP',
                "gender": 'female',
                "genderswap": 'variants_gabrielap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gabrielgbap',
                "message": '',
                "ageswap": 'variants_gabrielgb',
                "gender_age_swap": 'characters_ST/gabriel',
            },
        ],
    },

    # Genny
    {
        "default_character": 'characters_ST/genny',
        "variants": [
            {
                "name": 'GennyAP',
                "gender": 'female',
                "genderswap": 'variants_gennygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gennyap',
                "message": '',
                "ageswap": 'characters_ST/genny',
                "gender_age_swap": 'variants_gennygb',
            },
            {
                "name": 'GennyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/genny',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gennygb',
                "message": '',
                "ageswap": 'variants_gennygbap',
                "gender_age_swap": 'variants_gennyap',
            },
            {
                "name": 'GennyGBAP',
                "gender": 'male',
                "genderswap": 'variants_gennyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gennygbap',
                "message": '',
                "ageswap": 'variants_gennygb',
                "gender_age_swap": 'characters_ST/genny',
            },
        ],
    },

    # Grace
    {
        "default_character": 'characters_ST/grace',
        "variants": [
            {
                "name": 'GraceAR',
                "gender": 'female',
                "genderswap": 'variants_gracegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gracear',
                "message": '',
                "ageswap": 'characters_ST/grace',
                "gender_age_swap": 'variants_gracegb',
            },
            {
                "name": 'GraceGB',
                "gender": 'male',
                "genderswap": 'characters_ST/grace',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gracegb',
                "message": '',
                "ageswap": 'variants_gracegbar',
                "gender_age_swap": 'variants_gracear',
            },
            {
                "name": 'GraceGBAR',
                "gender": 'male',
                "genderswap": 'variants_gracear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gracegbar',
                "message": '',
                "ageswap": 'variants_gracegb',
                "gender_age_swap": 'characters_ST/grace',
            },
        ],
    },

    # Greg
    {
        "default_character": 'characters_ST/greg',
        "variants": [
            {
                "name": 'GregAR',
                "gender": 'male',
                "genderswap": 'variants_greggbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gregar',
                "message": '',
                "ageswap": 'characters_ST/greg',
                "gender_age_swap": 'variants_greggb',
            },
            {
                "name": 'GregGB',
                "gender": 'female',
                "genderswap": 'characters_ST/greg',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_greggb',
                "message": '',
                "ageswap": 'variants_greggbar',
                "gender_age_swap": 'variants_gregar',
            },
            {
                "name": 'GregGBAR',
                "gender": 'female',
                "genderswap": 'variants_gregar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_greggbar',
                "message": '',
                "ageswap": 'variants_greggb',
                "gender_age_swap": 'characters_ST/greg',
            },
        ],
    },

    # Gwen
    {
        "default_character": 'characters_ST/gwen',
        "variants": [
            {
                "name": 'GwenAR',
                "gender": 'female',
                "genderswap": 'variants_gwengbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gwenar',
                "message": '',
                "ageswap": 'characters_ST/gwen',
                "gender_age_swap": 'variants_gwengb',
            },
            {
                "name": 'GwenGB',
                "gender": 'male',
                "genderswap": 'characters_ST/gwen',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gwengb',
                "message": '',
                "ageswap": 'variants_gwengbar',
                "gender_age_swap": 'variants_gwenar',
            },
            {
                "name": 'GwenGBAR',
                "gender": 'male',
                "genderswap": 'variants_gwenar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_gwengbar',
                "message": '',
                "ageswap": 'variants_gwengb',
                "gender_age_swap": 'characters_ST/gwen',
            },
        ],
    },

    # Hank
    {
        "default_character": 'characters_ST/hank',
        "variants": [
            {
                "name": 'HankAR',
                "gender": 'male',
                "genderswap": 'variants_hankgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hankar',
                "message": '',
                "ageswap": 'characters_ST/hank',
                "gender_age_swap": 'variants_hankgb',
            },
            {
                "name": 'HankGB',
                "gender": 'female',
                "genderswap": 'characters_ST/hank',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hankgb',
                "message": '',
                "ageswap": 'variants_hankgbar',
                "gender_age_swap": 'variants_hankar',
            },
            {
                "name": 'HankGBAR',
                "gender": 'female',
                "genderswap": 'variants_hankar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hankgbar',
                "message": '',
                "ageswap": 'variants_hankgb',
                "gender_age_swap": 'characters_ST/hank',
            },
        ],
    },

    # Holly
    {
        "default_character": 'characters_ST/holly',
        "variants": [
            {
                "name": 'HollyAR',
                "gender": 'female',
                "genderswap": 'variants_hollygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hollyar',
                "message": '',
                "ageswap": 'characters_ST/holly',
                "gender_age_swap": 'variants_hollygb',
            },
            {
                "name": 'HollyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/holly',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hollygb',
                "message": '',
                "ageswap": 'variants_hollygbar',
                "gender_age_swap": 'variants_hollyar',
            },
            {
                "name": 'HollyGBAR',
                "gender": 'male',
                "genderswap": 'variants_hollyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_hollygbar',
                "message": '',
                "ageswap": 'variants_hollygb',
                "gender_age_swap": 'characters_ST/holly',
            },
        ],
    },

    # Irene
    {
        "default_character": 'characters_ST/irene',
        "variants": [
            {
                "name": 'IreneAP',
                "gender": 'female',
                "genderswap": 'variants_irenegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ireneap',
                "message": '',
                "ageswap": 'characters_ST/irene',
                "gender_age_swap": 'variants_irenegb',
            },
            {
                "name": 'IreneGB',
                "gender": 'male',
                "genderswap": 'characters_ST/irene',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_irenegb',
                "message": '',
                "ageswap": 'variants_irenegbap',
                "gender_age_swap": 'variants_ireneap',
            },
            {
                "name": 'IreneGBAP',
                "gender": 'male',
                "genderswap": 'variants_ireneap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_irenegbap',
                "message": '',
                "ageswap": 'variants_irenegb',
                "gender_age_swap": 'characters_ST/irene',
            },
        ],
    },

    # Izuna
    {
        "default_character": 'characters_ST/izuna',
        "variants": [
            {
                "name": 'IzunaAP',
                "gender": 'female',
                "genderswap": 'variants_izunagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_izunaap',
                "message": '',
                "ageswap": 'characters_ST/izuna',
                "gender_age_swap": 'variants_izunagb',
            },
            {
                "name": 'IzunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/izuna',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_izunagb',
                "message": '',
                "ageswap": 'variants_izunagbap',
                "gender_age_swap": 'variants_izunaap',
            },
            {
                "name": 'IzunaGBAP',
                "gender": 'male',
                "genderswap": 'variants_izunaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_izunagbap',
                "message": '',
                "ageswap": 'variants_izunagb',
                "gender_age_swap": 'characters_ST/izuna',
            },
        ],
    },

    # Jack
    {
        "default_character": 'characters_ST/jack',
        "variants": [
            {
                "name": 'JackAR',
                "gender": 'male',
                "genderswap": 'variants_jackgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_jackar',
                "message": '',
                "ageswap": 'characters_ST/jack',
                "gender_age_swap": 'variants_jackgb',
            },
            {
                "name": 'JackGB',
                "gender": 'female',
                "genderswap": 'characters_ST/jack',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_jackgb',
                "message": '',
                "ageswap": 'variants_jackgbar',
                "gender_age_swap": 'variants_jackar',
            },
            {
                "name": 'JackGBAR',
                "gender": 'female',
                "genderswap": 'variants_jackar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_jackgbar',
                "message": '',
                "ageswap": 'variants_jackgb',
                "gender_age_swap": 'characters_ST/jack',
            },
        ],
    },

    # John
    {
        "default_character": 'characters_ST/john',
        "variants": [
            {
                "name": 'JohnGBAP',
                "gender": 'female',
                "genderswap": 'variants_johnap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_johngbap',
                "message": '',
                "ageswap": 'characters_ST/johnGB',
                "gender_age_swap": 'characters_ST/john',
            },
            {
                "name": 'JohnAP',
                "gender": 'male',
                "genderswap": 'variants_johngbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_johnap',
                "message": '',
                "ageswap": 'characters_ST/john',
                "gender_age_swap": 'characters_ST/johnGB',
            },
        ],
    },

    # Katrina
    {
        "default_character": 'characters_ST/katrina',
        "variants": [
            {
                "name": 'KatrinaAP',
                "gender": 'female',
                "genderswap": 'variants_katgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_katap',
                "message": '',
                "ageswap": 'characters_ST/katrina',
                "gender_age_swap": 'characters_ST/katrinaGB',
            },
            {
                "name": 'KatrinaGBAP',
                "gender": 'male',
                "genderswap": 'variants_katap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_katgbap',
                "message": '',
                "ageswap": 'characters_ST/katrinaGB',
                "gender_age_swap": 'characters_ST/katrina',
            },
        ],
    },

    # Kiyoshi
    {
        "default_character": 'characters_ST/kiyoshi',
        "variants": [
            {
                "name": 'KiyoshiAP',
                "gender": 'male',
                "genderswap": 'variants_kiyoshigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_kiyoshiap',
                "message": '',
                "ageswap": 'characters_ST/kiyoshi',
                "gender_age_swap": 'characters_ST/kiyoshiGB',
            },
            {
                "name": 'KiyoshiGBAP',
                "gender": 'female',
                "genderswap": 'variants_kiyoshiap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_kiyoshigbap',
                "message": '',
                "ageswap": 'characters_ST/kiyoshiGB',
                "gender_age_swap": 'characters_ST/kiyoshi',
            },
        ],
    },

    # Kyoko
    {
        "default_character": 'characters_ST/kyoko',
        "variants": [
            {
                "name": 'KyokoAP',
                "gender": 'female',
                "genderswap": 'variants_kyokogbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_kyokoap',
                "message": '',
                "ageswap": 'characters_ST/kyoko',
                "gender_age_swap": 'variants_kyokogb',
            },
            {
                "name": 'KyokoGB',
                "gender": 'male',
                "genderswap": 'characters_ST/kyoko',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_kyokogb',
                "message": '',
                "ageswap": 'variants_kyokogbap',
                "gender_age_swap": 'variants_kyokoap',
            },
            {
                "name": 'KyokoGBAP',
                "gender": 'male',
                "genderswap": 'variants_kyokoap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_kyokogbap',
                "message": '',
                "ageswap": 'variants_kyokogb',
                "gender_age_swap": 'characters_ST/kyoko',
            },
        ],
    },

    # Laura
    {
        "default_character": 'characters_ST/laura',
        "variants": [
            {
                "name": 'LauraAR',
                "gender": 'female',
                "genderswap": 'variants_lauragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_lauraar',
                "message": '',
                "ageswap": 'characters_ST/laura',
                "gender_age_swap": 'variants_lauragb',
            },
            {
                "name": 'LauraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/laura',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_lauragb',
                "message": '',
                "ageswap": 'variants_lauragbar',
                "gender_age_swap": 'variants_lauraar',
            },
            {
                "name": 'LauraGBAR',
                "gender": 'male',
                "genderswap": 'variants_lauraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_lauragbar',
                "message": '',
                "ageswap": 'variants_lauragb',
                "gender_age_swap": 'characters_ST/laura',
            },
        ],
    },

    # Leona
    {
        "default_character": 'characters_ST/leona',
        "variants": [
            {
                "name": 'LeonaAR',
                "gender": 'female',
                "genderswap": 'variants_leonagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_leonaar',
                "message": '',
                "ageswap": 'characters_ST/leona',
                "gender_age_swap": 'variants_leonagb',
            },
            {
                "name": 'LeonaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/leona',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_leonagb',
                "message": '',
                "ageswap": 'variants_leonagbar',
                "gender_age_swap": 'variants_leonaar',
            },
            {
                "name": 'LeonaGBAR',
                "gender": 'male',
                "genderswap": 'variants_leonaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_leonagbar',
                "message": '',
                "ageswap": 'variants_leonagb',
                "gender_age_swap": 'characters_ST/leona',
            },
        ],
    },

    # Maria
    {
        "default_character": 'characters_ST/maria',
        "variants": [
            {
                "name": 'MariaAP',
                "gender": 'female',
                "genderswap": 'variants_mariagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mariaap',
                "message": '',
                "ageswap": 'characters_ST/maria',
                "gender_age_swap": 'variants_mariagb',
            },
            {
                "name": 'MariaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/maria',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mariagb',
                "message": '',
                "ageswap": 'variants_mariagbap',
                "gender_age_swap": 'variants_mariaap',
            },
            {
                "name": 'MariaGBAP',
                "gender": 'male',
                "genderswap": 'variants_mariaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mariagbap',
                "message": '',
                "ageswap": 'variants_mariagb',
                "gender_age_swap": 'characters_ST/maria',
            },
        ],
    },

    # Marty
    {
        "default_character": 'characters_ST/marty',
        "variants": [
            {
                "name": 'MartyAR',
                "gender": 'male',
                "genderswap": 'variants_martygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_martyar',
                "message": '',
                "ageswap": 'characters_ST/marty',
                "gender_age_swap": 'variants_martygb',
            },
            {
                "name": 'MartyGB',
                "gender": 'female',
                "genderswap": 'characters_ST/marty',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_martygb',
                "message": '',
                "ageswap": 'variants_martygbar',
                "gender_age_swap": 'variants_martyar',
            },
            {
                "name": 'MartyGBAR',
                "gender": 'female',
                "genderswap": 'variants_martyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_martygbar',
                "message": '',
                "ageswap": 'variants_martygb',
                "gender_age_swap": 'characters_ST/marty',
            },
        ],
    },

    # Matt
    {
        "default_character": 'characters_ST/matt',
        "variants": [
            {
                "name": 'MattAR',
                "gender": 'male',
                "genderswap": 'variants_mattgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mattar',
                "message": '',
                "ageswap": 'characters_ST/matt',
                "gender_age_swap": 'variants_mattgb',
            },
            {
                "name": 'MattGB',
                "gender": 'female',
                "genderswap": 'characters_ST/matt',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mattgb',
                "message": '',
                "ageswap": 'variants_mattgbar',
                "gender_age_swap": 'variants_mattar',
            },
            {
                "name": 'MattGBAR',
                "gender": 'female',
                "genderswap": 'variants_mattar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mattgbar',
                "message": '',
                "ageswap": 'variants_mattgb',
                "gender_age_swap": 'characters_ST/matt',
            },
        ],
    },

    # Maurice
    {
        "default_character": 'characters_ST/maurice',
        "variants": [
            {
                "name": 'MauriceAR',
                "gender": 'male',
                "genderswap": 'variants_mauricegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mauricear',
                "message": '',
                "ageswap": 'characters_ST/maurice',
                "gender_age_swap": 'variants_mauricegb',
            },
            {
                "name": 'MauriceGB',
                "gender": 'female',
                "genderswap": 'characters_ST/maurice',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mauricegb',
                "message": '',
                "ageswap": 'variants_mauricegbar',
                "gender_age_swap": 'variants_mauricear',
            },
            {
                "name": 'MauriceGBAR',
                "gender": 'female',
                "genderswap": 'variants_mauricear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_mauricegbar',
                "message": '',
                "ageswap": 'variants_mauricegb',
                "gender_age_swap": 'characters_ST/maurice',
            },
        ],
    },

    # Mel
    {
        "default_character": 'characters_ST/mel',
        "variants": [
            {
                "name": 'MelAP',
                "gender": 'female',
                "genderswap": 'variants_melgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_melap',
                "message": '',
                "ageswap": 'characters_ST/mel',
                "gender_age_swap": 'variants_melgb',
            },
            {
                "name": 'MelGB',
                "gender": 'male',
                "genderswap": 'characters_ST/mel',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_melgb',
                "message": '',
                "ageswap": 'variants_melgbap',
                "gender_age_swap": 'variants_melap',
            },
            {
                "name": 'MelGBAP',
                "gender": 'male',
                "genderswap": 'variants_melap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_melgbap',
                "message": '',
                "ageswap": 'variants_melgb',
                "gender_age_swap": 'characters_ST/mel',
            },
        ],
    },

    # Michelle
    {
        "default_character": 'characters_ST/michelle',
        "variants": [
            {
                "name": 'MichelleAP',
                "gender": 'female',
                "genderswap": 'variants_michellegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_michelleap',
                "message": '',
                "ageswap": 'characters_ST/michelle',
                "gender_age_swap": 'variants_michellegb',
            },
            {
                "name": 'MichelleGB',
                "gender": 'male',
                "genderswap": 'characters_ST/michelle',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_michellegb',
                "message": '',
                "ageswap": 'variants_michellegbap',
                "gender_age_swap": 'variants_michelleap',
            },
            {
                "name": 'MichelleGBAP',
                "gender": 'male',
                "genderswap": 'variants_michelleap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_michellegbap',
                "message": '',
                "ageswap": 'variants_michellegb',
                "gender_age_swap": 'characters_ST/michelle',
            },
        ],
    },

    # Mina
    {
        "default_character": 'characters_ST/mina',
        "variants": [
            {
                "name": 'MinaAP',
                "gender": 'female',
                "genderswap": 'variants_minagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_minaap',
                "message": '',
                "ageswap": 'characters_ST/mina',
                "gender_age_swap": 'variants_minagb',
            },
            {
                "name": 'MinaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/mina',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_minagb',
                "message": '',
                "ageswap": 'variants_minagbap',
                "gender_age_swap": 'variants_minaap',
            },
            {
                "name": 'MinaGBAP',
                "gender": 'male',
                "genderswap": 'variants_minaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_minagbap',
                "message": '',
                "ageswap": 'variants_minagb',
                "gender_age_swap": 'characters_ST/mina',
            },
        ],
    },

    # Naomi
    {
        "default_character": 'characters_ST/naomi',
        "variants": [
            {
                "name": 'NaomiAR',
                "gender": 'female',
                "genderswap": 'variants_naomigbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_naomiar',
                "message": '',
                "ageswap": 'characters_ST/naomi',
                "gender_age_swap": 'variants_naomigb',
            },
            {
                "name": 'NaomiGB',
                "gender": 'male',
                "genderswap": 'characters_ST/naomi',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_naomigb',
                "message": '',
                "ageswap": 'variants_naomigbar',
                "gender_age_swap": 'variants_naomiar',
            },
            {
                "name": 'NaomiGBAR',
                "gender": 'male',
                "genderswap": 'variants_naomiar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_naomigbar',
                "message": '',
                "ageswap": 'variants_naomigb',
                "gender_age_swap": 'characters_ST/naomi',
            },
        ],
    },

    # Nemuri
    {
        "default_character": 'characters_ST/nemuri',
        "variants": [
            {
                "name": 'NemuriAR',
                "gender": 'male',
                "genderswap": 'variants_nemurigbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_nemuriar',
                "message": '',
                "ageswap": 'characters_ST/nemuri',
                "gender_age_swap": 'variants_nemurigb',
            },
            {
                "name": 'NemuriGB',
                "gender": 'female',
                "genderswap": 'characters_ST/nemuri',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_nemurigb',
                "message": '',
                "ageswap": 'variants_nemurigbar',
                "gender_age_swap": 'variants_nemuriar',
            },
            {
                "name": 'NemuriGBAR',
                "gender": 'female',
                "genderswap": 'variants_nemuriar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_nemurigbar',
                "message": '',
                "ageswap": 'variants_nemurigb',
                "gender_age_swap": 'characters_ST/nemuri',
            },
        ],
    },

    # Nora
    {
        "default_character": 'characters_ST/nora',
        "variants": [
            {
                "name": 'NoraAR',
                "gender": 'female',
                "genderswap": 'variants_noragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_noraar',
                "message": '',
                "ageswap": 'characters_ST/nora',
                "gender_age_swap": 'variants_noragb',
            },
            {
                "name": 'NoraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/nora',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_noragb',
                "message": '',
                "ageswap": 'variants_noragbar',
                "gender_age_swap": 'variants_noraar',
            },
            {
                "name": 'NoraGBAR',
                "gender": 'male',
                "genderswap": 'variants_noraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_noragbar',
                "message": '',
                "ageswap": 'variants_noragb',
                "gender_age_swap": 'characters_ST/nora',
            },
        ],
    },

    # Paul
    {
        "default_character": 'characters_ST/paul',
        "variants": [
            {
                "name": 'PaulAR',
                "gender": 'male',
                "genderswap": 'variants_paulgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_paular',
                "message": '',
                "ageswap": 'characters_ST/paul',
                "gender_age_swap": 'variants_paulgb',
            },
            {
                "name": 'PaulGB',
                "gender": 'female',
                "genderswap": 'characters_ST/paul',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_paulgb',
                "message": '',
                "ageswap": 'variants_paulgbar',
                "gender_age_swap": 'variants_paular',
            },
            {
                "name": 'PaulGBAR',
                "gender": 'female',
                "genderswap": 'variants_paular',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_paulgbar',
                "message": '',
                "ageswap": 'variants_paulgb',
                "gender_age_swap": 'characters_ST/paul',
            },
        ],
    },

    # Phila
    {
        "default_character": 'characters_ST/phila',
        "variants": [
            {
                "name": 'PhilaAP',
                "gender": 'female',
                "genderswap": 'variants_philagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_philaap',
                "message": '',
                "ageswap": 'characters_ST/phila',
                "gender_age_swap": 'variants_philagb',
            },
            {
                "name": 'PhilaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/phila',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_philagb',
                "message": '',
                "ageswap": 'variants_philagbap',
                "gender_age_swap": 'variants_philaap',
            },
            {
                "name": 'PhilaGBAP',
                "gender": 'male',
                "genderswap": 'variants_philaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_philagbap',
                "message": '',
                "ageswap": 'variants_philagb',
                "gender_age_swap": 'characters_ST/phila',
            },
        ],
    },

    # Rachel
    {
        "default_character": 'characters_ST/rachel',
        "variants": [
            {
                "name": 'RachelAR',
                "gender": 'female',
                "genderswap": 'variants_rachelgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rachelar',
                "message": '',
                "ageswap": 'characters_ST/rachel',
                "gender_age_swap": 'variants_rachelgb',
            },
            {
                "name": 'RachelGB',
                "gender": 'male',
                "genderswap": 'characters_ST/rachel',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rachelgb',
                "message": '',
                "ageswap": 'variants_rachelgbar',
                "gender_age_swap": 'variants_rachelar',
            },
            {
                "name": 'RachelGBAR',
                "gender": 'male',
                "genderswap": 'variants_rachelar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rachelgbar',
                "message": '',
                "ageswap": 'variants_rachelgb',
                "gender_age_swap": 'characters_ST/rachel',
            },
        ],
    },

    # Riley
    {
        "default_character": 'characters_ST/riley',
        "variants": [
            {
                "name": 'RileyAP',
                "gender": 'male',
                "genderswap": 'variants_rileygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rileyap',
                "message": '',
                "ageswap": 'characters_ST/riley',
                "gender_age_swap": 'variants_rileygb',
            },
            {
                "name": 'RileyGB',
                "gender": 'female',
                "genderswap": 'characters_ST/riley',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rileygb',
                "message": '',
                "ageswap": 'variants_rileygbap',
                "gender_age_swap": 'variants_rileyap',
            },
            {
                "name": 'RileyGBAP',
                "gender": 'female',
                "genderswap": 'variants_rileyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_rileygbap',
                "message": '',
                "ageswap": 'variants_rileygb',
                "gender_age_swap": 'characters_ST/riley',
            },
        ],
    },

    # Rita
    {
        "default_character": 'characters_ST/rita',
        "variants": [
            {
                "name": 'RitaAP',
                "gender": 'female',
                "genderswap": 'variants_ritagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ritaap',
                "message": '',
                "ageswap": 'characters_ST/rita',
                "gender_age_swap": 'variants_ritagb',
            },
            {
                "name": 'RitaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/rita',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ritagb',
                "message": '',
                "ageswap": 'variants_ritagbap',
                "gender_age_swap": 'variants_ritaap',
            },
            {
                "name": 'RitaGBAP',
                "gender": 'male',
                "genderswap": 'variants_ritaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_ritagbap',
                "message": '',
                "ageswap": 'variants_ritagb',
                "gender_age_swap": 'characters_ST/rita',
            },
        ],
    },

    # Sadie
    {
        "default_character": 'characters_ST/sadie',
        "variants": [
            {
                "name": 'SadieAP',
                "gender": 'female',
                "genderswap": 'variants_sadiegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sadieap',
                "message": '',
                "ageswap": 'characters_ST/sadie',
                "gender_age_swap": 'variants_sadiegb',
            },
            {
                "name": 'SadieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/sadie',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sadiegb',
                "message": '',
                "ageswap": 'variants_sadiegbap',
                "gender_age_swap": 'variants_sadieap',
            },
            {
                "name": 'SadieGBAP',
                "gender": 'male',
                "genderswap": 'variants_sadieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sadiegbap',
                "message": '',
                "ageswap": 'variants_sadiegb',
                "gender_age_swap": 'characters_ST/sadie',
            },
        ],
    },

    # Sandra
    {
        "default_character": 'characters_ST/sandra',
        "variants": [
            {
                "name": 'SandraAR',
                "gender": 'female',
                "genderswap": 'variants_sandragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sandraar',
                "message": '',
                "ageswap": 'characters_ST/sandra',
                "gender_age_swap": 'variants_sandragb',
            },
            {
                "name": 'SandraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/sandra',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sandragb',
                "message": '',
                "ageswap": 'variants_sandragbar',
                "gender_age_swap": 'variants_sandraar',
            },
            {
                "name": 'SandraGBAR',
                "gender": 'male',
                "genderswap": 'variants_sandraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sandragbar',
                "message": '',
                "ageswap": 'variants_sandragb',
                "gender_age_swap": 'characters_ST/sandra',
            },
        ],
    },

    # Sayaka
    {
        "default_character": 'characters_ST/sayaka',
        "variants": [
            {
                "name": 'SayakaAP',
                "gender": 'female',
                "genderswap": 'variants_sayakagbar',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sayakaap',
                "message": '',
                "ageswap": 'characters_ST/sayaka',
                "gender_age_swap": 'variants_sayakagb',
            },
            {
                "name": 'SayakaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/sayaka',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sayakagb',
                "message": '',
                "ageswap": 'variants_sayakagbar',
                "gender_age_swap": 'variants_sayakaap',
            },
            {
                "name": 'SayakaGBAR',
                "gender": 'male',
                "genderswap": 'variants_sayakaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_sayakagbar',
                "message": '',
                "ageswap": 'variants_sayakagb',
                "gender_age_swap": 'characters_ST/sayaka',
            },
        ],
    },

    # Scarlet
    {
        "default_character": 'characters_ST/scarlet',
        "variants": [
            {
                "name": 'ScarletAR',
                "gender": 'female',
                "genderswap": 'variants_scarletgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_scarletar',
                "message": '',
                "ageswap": 'characters_ST/scarlet',
                "gender_age_swap": 'variants_scarletgb',
            },
            {
                "name": 'ScarletGB',
                "gender": 'male',
                "genderswap": 'characters_ST/scarlet',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_scarletgb',
                "message": '',
                "ageswap": 'variants_scarletgbar',
                "gender_age_swap": 'variants_scarletar',
            },
            {
                "name": 'ScarletGBAR',
                "gender": 'male',
                "genderswap": 'variants_scarletar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_scarletgbar',
                "message": '',
                "ageswap": 'variants_scarletgb',
                "gender_age_swap": 'characters_ST/scarlet',
            },
        ],
    },

    # Setsuna
    {
        "default_character": 'characters_ST/setsuna',
        "variants": [
            {
                "name": 'SetsunaAP',
                "gender": 'female',
                "genderswap": 'variants_setsunagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_setsunaap',
                "message": '',
                "ageswap": 'characters_ST/setsuna',
                "gender_age_swap": 'variants_setsunagb',
            },
            {
                "name": 'SetsunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/setsuna',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_setsunagb',
                "message": '',
                "ageswap": 'variants_setsunagbap',
                "gender_age_swap": 'variants_setsunaap',
            },
            {
                "name": 'SetsunaGBAP',
                "gender": 'male',
                "genderswap": 'variants_setsunaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_setsunagbap',
                "message": '',
                "ageswap": 'variants_setsunagb',
                "gender_age_swap": 'characters_ST/setsuna',
            },
        ],
    },

    # Stevie
    {
        "default_character": 'characters_ST/stevie',
        "variants": [
            {
                "name": 'Stevie',
                "gender": 'male',
                "genderswap": 'variants_steviegb',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_stevie',
                "message": '',
                "ageswap": 'variants_stevieap',
                "gender_age_swap": 'variants_steviegbap',
            },
            {
                "name": 'StevieAP',
                "gender": 'male',
                "genderswap": 'variants_steviegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_stevieap',
                "message": '',
                "ageswap": 'characters_ST/stevie',
                "gender_age_swap": 'variants_steviegb',
            },
            {
                "name": 'StevieGB',
                "gender": 'female',
                "genderswap": 'characters_ST/stevie',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_steviegb',
                "message": '',
                "ageswap": 'variants_steviegbap',
                "gender_age_swap": 'variants_stevieap',
            },
            {
                "name": 'StevieGBAP',
                "gender": 'female',
                "genderswap": 'variants_stevieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_steviegbap',
                "message": '',
                "ageswap": 'variants_steviegb',
                "gender_age_swap": 'characters_ST/stevie',
            },
        ],
    },

    # Tori
    {
        "default_character": 'characters_ST/tori',
        "variants": [
            {
                "name": 'ToriAP',
                "gender": 'female',
                "genderswap": 'variants_torigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_toriap',
                "message": '',
                "ageswap": 'characters_ST/tori',
                "gender_age_swap": 'variants_torigb',
            },
            {
                "name": 'ToriGB',
                "gender": 'male',
                "genderswap": 'characters_ST/tori',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_torigb',
                "message": '',
                "ageswap": 'variants_torigbap',
                "gender_age_swap": 'variants_toriap',
            },
            {
                "name": 'ToriGBAP',
                "gender": 'male',
                "genderswap": 'variants_toriap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_torigbap',
                "message": '',
                "ageswap": 'variants_torigb',
                "gender_age_swap": 'characters_ST/tori',
            },
        ],
    },

    # Vanessa
    {
        "default_character": 'characters_ST/vanessa',
        "variants": [
            {
                "name": 'VanessaAP',
                "gender": 'female',
                "genderswap": 'variants_vanessagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_vanessaap',
                "message": '',
                "ageswap": 'characters_ST/vanessa',
                "gender_age_swap": 'variants_vanessagb',
            },
            {
                "name": 'VanessaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/vanessa',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_vanessagb',
                "message": '',
                "ageswap": 'variants_vanessagbap',
                "gender_age_swap": 'variants_vanessaap',
            },
            {
                "name": 'VanessaGBAP',
                "gender": 'male',
                "genderswap": 'variants_vanessaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_vanessagbap',
                "message": '',
                "ageswap": 'variants_vanessagb',
                "gender_age_swap": 'characters_ST/vanessa',
            },
        ],
    },

    # Yui
    {
        "default_character": 'characters_ST/yui',
        "variants": [
            {
                "name": 'YuiAP',
                "gender": 'female',
                "genderswap": 'variants_yuigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuiap',
                "message": '',
                "ageswap": 'characters_ST/yui',
                "gender_age_swap": 'variants_yuigb',
            },
            {
                "name": 'YuiGB',
                "gender": 'male',
                "genderswap": 'characters_ST/yui',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuigb',
                "message": '',
                "ageswap": 'variants_yuigbap',
                "gender_age_swap": 'variants_yuiap',
            },
            {
                "name": 'YuiGBAP',
                "gender": 'male',
                "genderswap": 'variants_yuiap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuigbap',
                "message": '',
                "ageswap": 'variants_yuigb',
                "gender_age_swap": 'characters_ST/yui',
            },
        ],
    },

    # Yuuna
    {
        "default_character": 'characters_ST/yuuna',
        "variants": [
            {
                "name": 'YuunaAR',
                "gender": 'female',
                "genderswap": 'variants_yuunagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuunaar',
                "message": '',
                "ageswap": 'characters_ST/yuuna',
                "gender_age_swap": 'variants_yuunagb',
            },
            {
                "name": 'YuunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/yuuna',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuunagb',
                "message": '',
                "ageswap": 'variants_yuunagbar',
                "gender_age_swap": 'variants_yuunaar',
            },
            {
                "name": 'YuunaGBAR',
                "gender": 'male',
                "genderswap": 'variants_yuunaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_yuunagbar',
                "message": '',
                "ageswap": 'variants_yuunagb',
                "gender_age_swap": 'characters_ST/yuuna',
            },
        ],
    },

    # Zoey
    {
        "default_character": 'characters_ST/zoey',
        "variants": [
            {
                "name": 'ZoeyAP',
                "gender": 'female',
                "genderswap": 'variants_zoeygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_zoeyap',
                "message": '',
                "ageswap": 'characters_ST/zoey',
                "gender_age_swap": 'variants_zoeygb',
            },
            {
                "name": 'ZoeyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/zoey',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_zoeygb',
                "message": '',
                "ageswap": 'variants_zoeygbap',
                "gender_age_swap": 'variants_zoeyap',
            },
            {
                "name": 'ZoeyGBAP',
                "gender": 'male',
                "genderswap": 'variants_zoeyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'variants_zoeygbap',
                "message": '',
                "ageswap": 'variants_zoeygb',
                "gender_age_swap": 'characters_ST/zoey',
            },
        ],
    },

]

# Flatten to a single list of 162 dicts for the loader (unchanged API).
TF_CHARACTERS = []
for _block in CHARACTER_BLOCKS:
    _dc = _block["default_character"]
    for _v in _block["variants"]:
        TF_CHARACTERS.append({**_v, "default_character": _dc})


