# ST Variants pack – variant character definitions only.
# Design and structure match characters_ST; message is blank; fallback to ST message at runtime via default_character.
# Do not add base_folder, age_teen_folder, or age_adult_folder. One pack reads the other.

## Pack link (separate section)
# This pack links to the ST pack. Variant entries use default_character (e.g. characters_ST/abby) to identify
# the base character; when message is blank, the loader uses the ST message for that character.
# ST pack must be present and enabled for this pack to function.

import os

# Bot name from environment, defaults to "Syn" for backwards compatibility
BOT_NAME = os.getenv("TFBOT_NAME", "Syn").strip() or "Syn"

# Helper function to replace bot name placeholder in messages
def _format_message(message: str) -> str:
    """Replace {BOT_NAME} placeholder with actual bot name."""
    return message.replace("{BOT_NAME}", BOT_NAME)

# One block per base character; variants inherit default_character from the block.
CHARACTER_BLOCKS = [
    # Abby
    {
        "default_character": 'characters_ST/abby',
        "variants": [
            {
                "name": 'AbbyAR',
                "gender": 'female',
                "genderswap": 'abbygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'abbyar',
                "message": '',
                "ageswap": 'characters_ST/abby',
                "gender_age_swap": 'abbygb',
            },
            {
                "name": 'AbbyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/abby',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'abbygb',
                "message": '',
                "ageswap": 'abbygbar',
                "gender_age_swap": 'abbyar',
            },
            {
                "name": 'AbbyGBAR',
                "gender": 'male',
                "genderswap": 'abbyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'abbygbar',
                "message": '',
                "ageswap": 'abbygb',
                "gender_age_swap": 'characters_ST/abby',
            },
        ],
    },

    # Alex
    {
        "default_character": 'characters_ST/alex',
        "variants": [
            {
                "name": 'AlexAR',
                "gender": 'female',
                "genderswap": 'alexgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'alexar',
                "message": '',
                "ageswap": 'characters_ST/alex',
                "gender_age_swap": 'alexgb',
            },
            {
                "name": 'AlexGB',
                "gender": 'male',
                "genderswap": 'characters_ST/alex',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'alexgb',
                "message": '',
                "ageswap": 'alexgbar',
                "gender_age_swap": 'alexar',
            },
            {
                "name": 'AlexGBAR',
                "gender": 'male',
                "genderswap": 'alexar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'alexgbar',
                "message": '',
                "ageswap": 'alexgb',
                "gender_age_swap": 'characters_ST/alex',
            },
        ],
    },

    # Allison
    {
        "default_character": 'characters_ST/allison',
        "variants": [
            {
                "name": 'AllisonAP',
                "gender": 'female',
                "genderswap": 'allisongbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'allisonap',
                "message": '',
                "ageswap": 'characters_ST/allison',
                "gender_age_swap": 'allisongb',
            },
            {
                "name": 'AllisonGB',
                "gender": 'male',
                "genderswap": 'characters_ST/allison',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'allisongb',
                "message": '',
                "ageswap": 'allisongbap',
                "gender_age_swap": 'characters_ST/allison',
            },
            {
                "name": 'AllisonGBAP',
                "gender": 'male',
                "genderswap": 'allisonap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'allisongbap',
                "message": '',
                "ageswap": 'allisongb',
                "gender_age_swap": 'characters_ST/allison',
            },
        ],
    },

    # Anuja
    {
        "default_character": 'characters_ST/anuja',
        "variants": [
            {
                "name": 'AnujaAP',
                "gender": 'female',
                "genderswap": 'anujagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'anujaap',
                "message": '',
                "ageswap": 'characters_ST/anuja',
                "gender_age_swap": 'anujagb',
            },
            {
                "name": 'AnujaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/anuja',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'anujagb',
                "message": '',
                "ageswap": 'anujagbap',
                "gender_age_swap": 'characters_ST/anuja',
            },
            {
                "name": 'AnujaGBAP',
                "gender": 'male',
                "genderswap": 'anujaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'anujagbap',
                "message": '',
                "ageswap": 'anujagb',
                "gender_age_swap": 'characters_ST/anuja',
            },
        ],
    },

    # Audrey
    {
        "default_character": 'characters_ST/audrey',
        "variants": [
            {
                "name": 'AudreyAP',
                "gender": 'female',
                "genderswap": 'audreygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'audreyap',
                "message": '',
                "ageswap": 'characters_ST/audrey',
                "gender_age_swap": 'audreygb',
            },
            {
                "name": 'AudreyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/audrey',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'audreygb',
                "message": '',
                "ageswap": 'audreygbap',
                "gender_age_swap": 'characters_ST/audrey',
            },
            {
                "name": 'AudreyGBAP',
                "gender": 'male',
                "genderswap": 'audreyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'audreygbap',
                "message": '',
                "ageswap": 'audreygb',
                "gender_age_swap": 'characters_ST/audrey',
            },
        ],
    },

    # Brad
    {
        "default_character": 'characters_ST/brad',
        "variants": [
            {
                "name": 'BradAP',
                "gender": 'male',
                "genderswap": 'bradgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'bradap',
                "message": '',
                "ageswap": 'characters_ST/brad',
                "gender_age_swap": None,
            },
            {
                "name": 'BradGBAP',
                "gender": 'female',
                "genderswap": 'bradap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'bradgbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/brad',
            },
        ],
    },

    # Carla
    {
        "default_character": 'characters_ST/carla',
        "variants": [
            {
                "name": 'CarlaAR',
                "gender": 'female',
                "genderswap": 'carlagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'carlaar',
                "message": '',
                "ageswap": 'characters_ST/carla',
                "gender_age_swap": 'carlagb',
            },
            {
                "name": 'CarlaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/carla',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'carlagb',
                "message": '',
                "ageswap": 'carlagbar',
                "gender_age_swap": 'carlaar',
            },
            {
                "name": 'CarlaGBAR',
                "gender": 'male',
                "genderswap": 'carlaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'carlagbar',
                "message": '',
                "ageswap": 'carlagb',
                "gender_age_swap": 'characters_ST/carla',
            },
        ],
    },

    # Carrie
    {
        "default_character": 'characters_ST/carrie',
        "variants": [
            {
                "name": 'CarrieAP',
                "gender": 'female',
                "genderswap": 'carriegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'carrieap',
                "message": '',
                "ageswap": 'characters_ST/carrie',
                "gender_age_swap": None,
            },
            {
                "name": 'CarrieGBAP',
                "gender": 'male',
                "genderswap": 'carrieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'carriegbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/carrie',
            },
        ],
    },

    # Cassie
    {
        "default_character": 'characters_ST/cassie',
        "variants": [
            {
                "name": 'CassieAR',
                "gender": 'female',
                "genderswap": 'cassiegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'cassiear',
                "message": '',
                "ageswap": 'characters_ST/cassie',
                "gender_age_swap": 'cassiegb',
            },
            {
                "name": 'CassieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/cassie',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'cassiegb',
                "message": '',
                "ageswap": 'cassiegbar',
                "gender_age_swap": 'cassiear',
            },
            {
                "name": 'CassieGBAR',
                "gender": 'male',
                "genderswap": 'cassiear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'cassiegbar',
                "message": '',
                "ageswap": 'cassiegb',
                "gender_age_swap": 'characters_ST/cassie',
            },
        ],
    },

    # Charlotte
    {
        "default_character": 'characters_ST/charlotte',
        "variants": [
            {
                "name": 'CharlotteAR',
                "gender": 'female',
                "genderswap": 'charlottegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'charlottear',
                "message": '',
                "ageswap": 'characters_ST/charlotte',
                "gender_age_swap": 'charlottegb',
            },
            {
                "name": 'CharlotteGB',
                "gender": 'male',
                "genderswap": 'characters_ST/charlotte',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'charlottegb',
                "message": '',
                "ageswap": 'charlottegbar',
                "gender_age_swap": 'charlottear',
            },
            {
                "name": 'CharlotteGBAR',
                "gender": 'male',
                "genderswap": 'charlottear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'charlottegbar',
                "message": '',
                "ageswap": 'charlottegb',
                "gender_age_swap": 'characters_ST/charlotte',
            },
        ],
    },

    # Claus
    {
        "default_character": 'characters_ST/claus',
        "variants": [
            {
                "name": 'ClausGB',
                "gender": 'female',
                "genderswap": 'characters_ST/claus',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'clausgb',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/claus',
            },
        ],
    },

    # Connie
    {
        "default_character": 'characters_ST/connie',
        "variants": [
            {
                "name": 'ConnieAR',
                "gender": 'female',
                "genderswap": 'conniegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'conniear',
                "message": '',
                "ageswap": 'characters_ST/connie',
                "gender_age_swap": 'conniegb',
            },
            {
                "name": 'ConnieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/connie',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'conniegb',
                "message": '',
                "ageswap": 'conniegbar',
                "gender_age_swap": 'conniear',
            },
            {
                "name": 'ConnieGBAR',
                "gender": 'male',
                "genderswap": 'conniear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'conniegbar',
                "message": '',
                "ageswap": 'conniegb',
                "gender_age_swap": 'characters_ST/connie',
            },
        ],
    },

    # Dominic
    {
        "default_character": 'characters_ST/dominic',
        "variants": [
            {
                "name": 'DominicAR',
                "gender": 'male',
                "genderswap": 'dominicgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'dominicar',
                "message": '',
                "ageswap": 'characters_ST/dominic',
                "gender_age_swap": 'dominicgb',
            },
            {
                "name": 'DominicGB',
                "gender": 'female',
                "genderswap": 'characters_ST/dominic',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'dominicgb',
                "message": '',
                "ageswap": 'dominicgbar',
                "gender_age_swap": 'dominicar',
            },
            {
                "name": 'DominicGBAR',
                "gender": 'female',
                "genderswap": 'dominicar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'dominicgbar',
                "message": '',
                "ageswap": 'dominicgb',
                "gender_age_swap": 'characters_ST/dominic',
            },
        ],
    },

    # Donna
    {
        "default_character": 'characters_ST/donna',
        "variants": [
            {
                "name": 'DonnaAR',
                "gender": 'female',
                "genderswap": 'donnagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'donnaar',
                "message": '',
                "ageswap": 'characters_ST/donna',
                "gender_age_swap": 'donnagb',
            },
            {
                "name": 'DonnaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/donna',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'donnagb',
                "message": '',
                "ageswap": 'donnagbar',
                "gender_age_swap": 'donnaar',
            },
            {
                "name": 'DonnaGBAR',
                "gender": 'male',
                "genderswap": 'donnaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'donnagbar',
                "message": '',
                "ageswap": 'donnagb',
                "gender_age_swap": 'characters_ST/donna',
            },
        ],
    },

    # Elizabeth
    {
        "default_character": 'characters_ST/elizabeth',
        "variants": [
            {
                "name": 'ElizabethAR',
                "gender": 'female',
                "genderswap": 'elizabethgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'elizabethar',
                "message": '',
                "ageswap": 'characters_ST/elizabeth',
                "gender_age_swap": 'elizabethgb',
            },
            {
                "name": 'ElizabethGB',
                "gender": 'male',
                "genderswap": 'characters_ST/elizabeth',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'elizabethgb',
                "message": '',
                "ageswap": 'elizabethgbar',
                "gender_age_swap": 'elizabethar',
            },
            {
                "name": 'ElizabethGBAR',
                "gender": 'male',
                "genderswap": 'elizabethar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'elizabethgbar',
                "message": '',
                "ageswap": 'elizabethgb',
                "gender_age_swap": 'characters_ST/elizabeth',
            },
        ],
    },

    # Emily
    {
        "default_character": 'characters_ST/emily',
        "variants": [
            {
                "name": 'EmilyAP',
                "gender": 'female',
                "genderswap": 'emilygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'emilyap',
                "message": '',
                "ageswap": 'characters_ST/emily',
                "gender_age_swap": None,
            },
            {
                "name": 'EmilyGBAP',
                "gender": 'male',
                "genderswap": 'emilyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'emilygbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/emily',
            },
        ],
    },

    # Eric
    {
        "default_character": 'characters_ST/eric',
        "variants": [
            {
                "name": 'EricAP',
                "gender": 'male',
                "genderswap": 'ericgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'ericap',
                "message": '',
                "ageswap": 'characters_ST/eric',
                "gender_age_swap": None,
            },
            {
                "name": 'EricGBAP',
                "gender": 'female',
                "genderswap": 'ericap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'ericgbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/eric',
            },
        ],
    },

    # Gabriel
    {
        "default_character": 'characters_ST/gabriel',
        "variants": [
            {
                "name": 'GabrielAP',
                "gender": 'male',
                "genderswap": 'gabrielgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gabrielap',
                "message": '',
                "ageswap": 'characters_ST/gabriel',
                "gender_age_swap": 'gabrielgb',
            },
            {
                "name": 'GabrielGB',
                "gender": 'female',
                "genderswap": 'characters_ST/gabriel',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gabrielgb',
                "message": '',
                "ageswap": 'gabrielgbap',
                "gender_age_swap": 'characters_ST/gabriel',
            },
            {
                "name": 'GabrielGBAP',
                "gender": 'female',
                "genderswap": 'gabrielap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gabrielgbap',
                "message": '',
                "ageswap": 'gabrielgb',
                "gender_age_swap": 'characters_ST/gabriel',
            },
        ],
    },

    # Genny
    {
        "default_character": 'characters_ST/genny',
        "variants": [
            {
                "name": 'GennyAP',
                "gender": 'female',
                "genderswap": 'gennygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gennyap',
                "message": '',
                "ageswap": 'characters_ST/genny',
                "gender_age_swap": 'gennygb',
            },
            {
                "name": 'GennyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/genny',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gennygb',
                "message": '',
                "ageswap": 'gennygbap',
                "gender_age_swap": 'characters_ST/genny',
            },
            {
                "name": 'GennyGBAP',
                "gender": 'male',
                "genderswap": 'gennyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gennygbap',
                "message": '',
                "ageswap": 'gennygb',
                "gender_age_swap": 'characters_ST/genny',
            },
        ],
    },

    # Grace
    {
        "default_character": 'characters_ST/grace',
        "variants": [
            {
                "name": 'GraceAR',
                "gender": 'female',
                "genderswap": 'gracegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gracear',
                "message": '',
                "ageswap": 'characters_ST/grace',
                "gender_age_swap": 'gracegb',
            },
            {
                "name": 'GraceGB',
                "gender": 'male',
                "genderswap": 'characters_ST/grace',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gracegb',
                "message": '',
                "ageswap": 'gracegbar',
                "gender_age_swap": 'gracear',
            },
            {
                "name": 'GraceGBAR',
                "gender": 'male',
                "genderswap": 'gracear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gracegbar',
                "message": '',
                "ageswap": 'gracegb',
                "gender_age_swap": 'characters_ST/grace',
            },
        ],
    },

    # Greg
    {
        "default_character": 'characters_ST/greg',
        "variants": [
            {
                "name": 'GregAR',
                "gender": 'male',
                "genderswap": 'greggbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gregar',
                "message": '',
                "ageswap": 'characters_ST/greg',
                "gender_age_swap": 'greggb',
            },
            {
                "name": 'GregGB',
                "gender": 'female',
                "genderswap": 'characters_ST/greg',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'greggb',
                "message": '',
                "ageswap": 'greggbar',
                "gender_age_swap": 'gregar',
            },
            {
                "name": 'GregGBAR',
                "gender": 'female',
                "genderswap": 'gregar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'greggbar',
                "message": '',
                "ageswap": 'greggb',
                "gender_age_swap": 'characters_ST/greg',
            },
        ],
    },

    # Gwen
    {
        "default_character": 'characters_ST/gwen',
        "variants": [
            {
                "name": 'GwenAR',
                "gender": 'female',
                "genderswap": 'gwengbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gwenar',
                "message": '',
                "ageswap": 'characters_ST/gwen',
                "gender_age_swap": 'gwengb',
            },
            {
                "name": 'GwenGB',
                "gender": 'male',
                "genderswap": 'characters_ST/gwen',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gwengb',
                "message": '',
                "ageswap": 'gwengbar',
                "gender_age_swap": 'gwenar',
            },
            {
                "name": 'GwenGBAR',
                "gender": 'male',
                "genderswap": 'gwenar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'gwengbar',
                "message": '',
                "ageswap": 'gwengb',
                "gender_age_swap": 'characters_ST/gwen',
            },
        ],
    },

    # Hank
    {
        "default_character": 'characters_ST/hank',
        "variants": [
            {
                "name": 'HankAR',
                "gender": 'male',
                "genderswap": 'hankgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'hankar',
                "message": '',
                "ageswap": 'characters_ST/hank',
                "gender_age_swap": 'hankgb',
            },
            {
                "name": 'HankGB',
                "gender": 'female',
                "genderswap": 'characters_ST/hank',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'hankgb',
                "message": '',
                "ageswap": 'hankgbar',
                "gender_age_swap": 'hankar',
            },
            {
                "name": 'HankGBAR',
                "gender": 'female',
                "genderswap": 'hankar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'hankgbar',
                "message": '',
                "ageswap": 'hankgb',
                "gender_age_swap": 'characters_ST/hank',
            },
        ],
    },

    # Holly
    {
        "default_character": 'characters_ST/holly',
        "variants": [
            {
                "name": 'HollyAR',
                "gender": 'female',
                "genderswap": 'hollygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'hollyar',
                "message": '',
                "ageswap": 'characters_ST/holly',
                "gender_age_swap": None,
            },
            {
                "name": 'HollyGBAR',
                "gender": 'male',
                "genderswap": 'hollyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'hollygbar',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/holly',
            },
        ],
    },

    # Irene
    {
        "default_character": 'characters_ST/irene',
        "variants": [
            {
                "name": 'IreneGB',
                "gender": 'male',
                "genderswap": 'characters_ST/irene',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'irenegb',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/irene',
            },
        ],
    },

    # Izuna
    {
        "default_character": 'characters_ST/izuna',
        "variants": [
            {
                "name": 'IzunaAP',
                "gender": 'female',
                "genderswap": 'izunagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'izunaap',
                "message": '',
                "ageswap": 'characters_ST/izuna',
                "gender_age_swap": 'izunagb',
            },
            {
                "name": 'IzunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/izuna',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'izunagb',
                "message": '',
                "ageswap": 'izunagbap',
                "gender_age_swap": 'characters_ST/izuna',
            },
            {
                "name": 'IzunaGBAP',
                "gender": 'male',
                "genderswap": 'izunaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'izunagbap',
                "message": '',
                "ageswap": 'izunagb',
                "gender_age_swap": 'characters_ST/izuna',
            },
        ],
    },

    # Jack
    {
        "default_character": 'characters_ST/jack',
        "variants": [
            {
                "name": 'JackAR',
                "gender": 'male',
                "genderswap": 'jackgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'jackar',
                "message": '',
                "ageswap": 'characters_ST/jack',
                "gender_age_swap": 'jackgb',
            },
            {
                "name": 'JackGB',
                "gender": 'female',
                "genderswap": 'characters_ST/jack',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'jackgb',
                "message": '',
                "ageswap": 'jackgbar',
                "gender_age_swap": 'jackar',
            },
            {
                "name": 'JackGBAR',
                "gender": 'female',
                "genderswap": 'jackar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'jackgbar',
                "message": '',
                "ageswap": 'jackgb',
                "gender_age_swap": 'characters_ST/jack',
            },
        ],
    },

    # John
    {
        "default_character": 'characters_ST/john',
        "variants": [
            {
                "name": 'JohnGBAP',
                "gender": 'female',
                "genderswap": 'johnap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'johngbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/john',
            },
            {
                "name": 'JohnAP',
                "gender": 'male',
                "genderswap": 'johngbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'johnap',
                "message": '',
                "ageswap": 'characters_ST/john',
                "gender_age_swap": None,
            },
        ],
    },

    # Katrina
    {
        "default_character": 'characters_ST/katrina',
        "variants": [
            {
                "name": 'KatAP',
                "gender": 'female',
                "genderswap": 'katgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'katap',
                "message": '',
                "ageswap": 'characters_ST/katrina',
                "gender_age_swap": None,
            },
            {
                "name": 'KatGBAP',
                "gender": 'male',
                "genderswap": 'katap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'katgbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/katrina',
            },
        ],
    },

    # Kiyoshi
    {
        "default_character": 'characters_ST/kiyoshi',
        "variants": [
            {
                "name": 'KiyoshiAP',
                "gender": 'male',
                "genderswap": 'kiyoshigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'kiyoshiap',
                "message": '',
                "ageswap": 'characters_ST/kiyoshi',
                "gender_age_swap": None,
            },
            {
                "name": 'KiyoshiGBAP',
                "gender": 'female',
                "genderswap": 'kiyoshiap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'kiyoshigbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/kiyoshi',
            },
        ],
    },

    # Kyoko
    {
        "default_character": 'characters_ST/kyoko',
        "variants": [
            {
                "name": 'KyokoAP',
                "gender": 'female',
                "genderswap": 'kyokogbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'kyokoap',
                "message": '',
                "ageswap": 'characters_ST/kyoko',
                "gender_age_swap": 'kyokogb',
            },
            {
                "name": 'KyokoGB',
                "gender": 'male',
                "genderswap": 'characters_ST/kyoko',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'kyokogb',
                "message": '',
                "ageswap": 'kyokogbap',
                "gender_age_swap": 'characters_ST/kyoko',
            },
            {
                "name": 'KyokoGBAP',
                "gender": 'male',
                "genderswap": 'kyokoap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'kyokogbap',
                "message": '',
                "ageswap": 'kyokogb',
                "gender_age_swap": 'characters_ST/kyoko',
            },
        ],
    },

    # Laura
    {
        "default_character": 'characters_ST/laura',
        "variants": [
            {
                "name": 'LauraAR',
                "gender": 'female',
                "genderswap": 'lauragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'lauraar',
                "message": '',
                "ageswap": 'characters_ST/laura',
                "gender_age_swap": 'lauragb',
            },
            {
                "name": 'LauraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/laura',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'lauragb',
                "message": '',
                "ageswap": 'lauragbar',
                "gender_age_swap": 'lauraar',
            },
            {
                "name": 'LauraGBAR',
                "gender": 'male',
                "genderswap": 'lauraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'lauragbar',
                "message": '',
                "ageswap": 'lauragb',
                "gender_age_swap": 'characters_ST/laura',
            },
        ],
    },

    # Leona
    {
        "default_character": 'characters_ST/leona',
        "variants": [
            {
                "name": 'LeonaAR',
                "gender": 'female',
                "genderswap": 'leonagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'leonaar',
                "message": '',
                "ageswap": 'characters_ST/leona',
                "gender_age_swap": 'leonagb',
            },
            {
                "name": 'LeonaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/leona',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'leonagb',
                "message": '',
                "ageswap": 'leonagbar',
                "gender_age_swap": 'leonaar',
            },
            {
                "name": 'LeonaGBAR',
                "gender": 'male',
                "genderswap": 'leonaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'leonagbar',
                "message": '',
                "ageswap": 'leonagb',
                "gender_age_swap": 'characters_ST/leona',
            },
        ],
    },

    # Maria
    {
        "default_character": 'characters_ST/maria',
        "variants": [
            {
                "name": 'MariaAP',
                "gender": 'female',
                "genderswap": 'mariagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mariaap',
                "message": '',
                "ageswap": 'characters_ST/maria',
                "gender_age_swap": 'mariagb',
            },
            {
                "name": 'MariaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/maria',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mariagb',
                "message": '',
                "ageswap": 'mariagbap',
                "gender_age_swap": 'characters_ST/maria',
            },
            {
                "name": 'MariaGBAP',
                "gender": 'male',
                "genderswap": 'mariaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mariagbap',
                "message": '',
                "ageswap": 'mariagb',
                "gender_age_swap": 'characters_ST/maria',
            },
        ],
    },

    # Marty
    {
        "default_character": 'characters_ST/marty',
        "variants": [
            {
                "name": 'MartyAR',
                "gender": 'male',
                "genderswap": 'martygbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'martyar',
                "message": '',
                "ageswap": 'characters_ST/marty',
                "gender_age_swap": 'martygb',
            },
            {
                "name": 'MartyGB',
                "gender": 'female',
                "genderswap": 'characters_ST/marty',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'martygb',
                "message": '',
                "ageswap": 'martygbar',
                "gender_age_swap": 'martyar',
            },
            {
                "name": 'MartyGBAR',
                "gender": 'female',
                "genderswap": 'martyar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'martygbar',
                "message": '',
                "ageswap": 'martygb',
                "gender_age_swap": 'characters_ST/marty',
            },
        ],
    },

    # Matt
    {
        "default_character": 'characters_ST/matt',
        "variants": [
            {
                "name": 'MattAR',
                "gender": 'male',
                "genderswap": 'mattgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mattar',
                "message": '',
                "ageswap": 'characters_ST/matt',
                "gender_age_swap": 'mattgb',
            },
            {
                "name": 'MattGB',
                "gender": 'female',
                "genderswap": 'characters_ST/matt',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mattgb',
                "message": '',
                "ageswap": 'mattgbar',
                "gender_age_swap": 'mattar',
            },
            {
                "name": 'MattGBAR',
                "gender": 'female',
                "genderswap": 'mattar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mattgbar',
                "message": '',
                "ageswap": 'mattgb',
                "gender_age_swap": 'characters_ST/matt',
            },
        ],
    },

    # Maurice
    {
        "default_character": 'characters_ST/maurice',
        "variants": [
            {
                "name": 'MauriceAR',
                "gender": 'male',
                "genderswap": 'mauricegbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mauricear',
                "message": '',
                "ageswap": 'characters_ST/maurice',
                "gender_age_swap": 'mauricegb',
            },
            {
                "name": 'MauriceGB',
                "gender": 'female',
                "genderswap": 'characters_ST/maurice',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mauricegb',
                "message": '',
                "ageswap": 'mauricegbar',
                "gender_age_swap": 'mauricear',
            },
            {
                "name": 'MauriceGBAR',
                "gender": 'female',
                "genderswap": 'mauricear',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'mauricegbar',
                "message": '',
                "ageswap": 'mauricegb',
                "gender_age_swap": 'characters_ST/maurice',
            },
        ],
    },

    # Mel
    {
        "default_character": 'characters_ST/mel',
        "variants": [
            {
                "name": 'MelAP',
                "gender": 'female',
                "genderswap": 'melgbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'melap',
                "message": '',
                "ageswap": 'characters_ST/mel',
                "gender_age_swap": 'melgb',
            },
            {
                "name": 'MelGB',
                "gender": 'male',
                "genderswap": 'characters_ST/mel',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'melgb',
                "message": '',
                "ageswap": 'melgbap',
                "gender_age_swap": 'characters_ST/mel',
            },
            {
                "name": 'MelGBAP',
                "gender": 'male',
                "genderswap": 'melap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'melgbap',
                "message": '',
                "ageswap": 'melgb',
                "gender_age_swap": 'characters_ST/mel',
            },
        ],
    },

    # Michelle
    {
        "default_character": 'characters_ST/michelle',
        "variants": [
            {
                "name": 'MichelleAP',
                "gender": 'female',
                "genderswap": 'michellegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'michelleap',
                "message": '',
                "ageswap": 'characters_ST/michelle',
                "gender_age_swap": 'michellegb',
            },
            {
                "name": 'MichelleGB',
                "gender": 'male',
                "genderswap": 'characters_ST/michelle',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'michellegb',
                "message": '',
                "ageswap": 'michellegbap',
                "gender_age_swap": 'characters_ST/michelle',
            },
            {
                "name": 'MichelleGBAP',
                "gender": 'male',
                "genderswap": 'michelleap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'michellegbap',
                "message": '',
                "ageswap": 'michellegb',
                "gender_age_swap": 'characters_ST/michelle',
            },
        ],
    },

    # Mina
    {
        "default_character": 'characters_ST/mina',
        "variants": [
            {
                "name": 'MinaAP',
                "gender": 'female',
                "genderswap": 'minagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'minaap',
                "message": '',
                "ageswap": 'characters_ST/mina',
                "gender_age_swap": 'minagb',
            },
            {
                "name": 'MinaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/mina',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'minagb',
                "message": '',
                "ageswap": 'minagbap',
                "gender_age_swap": 'characters_ST/mina',
            },
            {
                "name": 'MinaGBAP',
                "gender": 'male',
                "genderswap": 'minaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'minagbap',
                "message": '',
                "ageswap": 'minagb',
                "gender_age_swap": 'characters_ST/mina',
            },
        ],
    },

    # Naomi
    {
        "default_character": 'characters_ST/naomi',
        "variants": [
            {
                "name": 'NaomiAR',
                "gender": 'female',
                "genderswap": 'naomigbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'naomiar',
                "message": '',
                "ageswap": 'characters_ST/naomi',
                "gender_age_swap": 'naomigb',
            },
            {
                "name": 'NaomiGB',
                "gender": 'male',
                "genderswap": 'characters_ST/naomi',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'naomigb',
                "message": '',
                "ageswap": 'naomigbar',
                "gender_age_swap": 'naomiar',
            },
            {
                "name": 'NaomiGBAR',
                "gender": 'male',
                "genderswap": 'naomiar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'naomigbar',
                "message": '',
                "ageswap": 'naomigb',
                "gender_age_swap": 'characters_ST/naomi',
            },
        ],
    },

    # Nemuri
    {
        "default_character": 'characters_ST/nemuri',
        "variants": [
            {
                "name": 'NemuriAR',
                "gender": 'male',
                "genderswap": 'nemurigbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'nemuriar',
                "message": '',
                "ageswap": 'characters_ST/nemuri',
                "gender_age_swap": 'nemurigb',
            },
            {
                "name": 'NemuriGB',
                "gender": 'female',
                "genderswap": 'characters_ST/nemuri',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'nemurigb',
                "message": '',
                "ageswap": 'nemurigbar',
                "gender_age_swap": 'nemuriar',
            },
            {
                "name": 'NemuriGBAR',
                "gender": 'female',
                "genderswap": 'nemuriar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'nemurigbar',
                "message": '',
                "ageswap": 'nemurigb',
                "gender_age_swap": 'characters_ST/nemuri',
            },
        ],
    },

    # Nora
    {
        "default_character": 'characters_ST/nora',
        "variants": [
            {
                "name": 'NoraAR',
                "gender": 'female',
                "genderswap": 'noragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'noraar',
                "message": '',
                "ageswap": 'characters_ST/nora',
                "gender_age_swap": 'noragb',
            },
            {
                "name": 'NoraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/nora',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'noragb',
                "message": '',
                "ageswap": 'noragbar',
                "gender_age_swap": 'noraar',
            },
            {
                "name": 'NoraGBAR',
                "gender": 'male',
                "genderswap": 'noraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'noragbar',
                "message": '',
                "ageswap": 'noragb',
                "gender_age_swap": 'characters_ST/nora',
            },
        ],
    },

    # Paul
    {
        "default_character": 'characters_ST/paul',
        "variants": [
            {
                "name": 'PaulAR',
                "gender": 'male',
                "genderswap": 'paulgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'paular',
                "message": '',
                "ageswap": 'characters_ST/paul',
                "gender_age_swap": 'paulgb',
            },
            {
                "name": 'PaulGB',
                "gender": 'female',
                "genderswap": 'characters_ST/paul',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'paulgb',
                "message": '',
                "ageswap": 'paulgbar',
                "gender_age_swap": 'paular',
            },
            {
                "name": 'PaulGBAR',
                "gender": 'female',
                "genderswap": 'paular',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'paulgbar',
                "message": '',
                "ageswap": 'paulgb',
                "gender_age_swap": 'characters_ST/paul',
            },
        ],
    },

    # Phila
    {
        "default_character": 'characters_ST/phila',
        "variants": [
            {
                "name": 'PhilaAP',
                "gender": 'female',
                "genderswap": 'philagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'philaap',
                "message": '',
                "ageswap": 'characters_ST/phila',
                "gender_age_swap": 'philagb',
            },
            {
                "name": 'PhilaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/phila',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'philagb',
                "message": '',
                "ageswap": 'philagbap',
                "gender_age_swap": 'characters_ST/phila',
            },
            {
                "name": 'PhilaGBAP',
                "gender": 'male',
                "genderswap": 'philaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'philagbap',
                "message": '',
                "ageswap": 'philagb',
                "gender_age_swap": 'characters_ST/phila',
            },
        ],
    },

    # Rachel
    {
        "default_character": 'characters_ST/rachel',
        "variants": [
            {
                "name": 'RachelAR',
                "gender": 'female',
                "genderswap": 'rachelgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rachelar',
                "message": '',
                "ageswap": 'characters_ST/rachel',
                "gender_age_swap": 'rachelgb',
            },
            {
                "name": 'RachelGB',
                "gender": 'male',
                "genderswap": 'characters_ST/rachel',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rachelgb',
                "message": '',
                "ageswap": 'rachelgbar',
                "gender_age_swap": 'rachelar',
            },
            {
                "name": 'RachelGBAR',
                "gender": 'male',
                "genderswap": 'rachelar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rachelgbar',
                "message": '',
                "ageswap": 'rachelgb',
                "gender_age_swap": 'characters_ST/rachel',
            },
        ],
    },

    # Riley
    {
        "default_character": 'characters_ST/riley',
        "variants": [
            {
                "name": 'RileyAP',
                "gender": 'male',
                "genderswap": 'rileygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rileyap',
                "message": '',
                "ageswap": 'characters_ST/riley',
                "gender_age_swap": 'rileygb',
            },
            {
                "name": 'RileyGB',
                "gender": 'female',
                "genderswap": 'characters_ST/riley',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rileygb',
                "message": '',
                "ageswap": 'rileygbap',
                "gender_age_swap": 'characters_ST/riley',
            },
            {
                "name": 'RileyGBAP',
                "gender": 'female',
                "genderswap": 'rileyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'rileygbap',
                "message": '',
                "ageswap": 'rileygb',
                "gender_age_swap": 'characters_ST/riley',
            },
        ],
    },

    # Rita
    {
        "default_character": 'characters_ST/rita',
        "variants": [
            {
                "name": 'RitaAP',
                "gender": 'female',
                "genderswap": 'ritagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'ritaap',
                "message": '',
                "ageswap": 'characters_ST/rita',
                "gender_age_swap": 'ritagb',
            },
            {
                "name": 'RitaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/rita',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'ritagb',
                "message": '',
                "ageswap": 'ritagbap',
                "gender_age_swap": 'characters_ST/rita',
            },
            {
                "name": 'RitaGBAP',
                "gender": 'male',
                "genderswap": 'ritaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'ritagbap',
                "message": '',
                "ageswap": 'ritagb',
                "gender_age_swap": 'characters_ST/rita',
            },
        ],
    },

    # Sadie
    {
        "default_character": 'characters_ST/sadie',
        "variants": [
            {
                "name": 'SadieAP',
                "gender": 'female',
                "genderswap": 'sadiegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sadieap',
                "message": '',
                "ageswap": 'characters_ST/sadie',
                "gender_age_swap": 'sadiegb',
            },
            {
                "name": 'SadieGB',
                "gender": 'male',
                "genderswap": 'characters_ST/sadie',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sadiegb',
                "message": '',
                "ageswap": 'sadiegbap',
                "gender_age_swap": 'characters_ST/sadie',
            },
            {
                "name": 'SadieGBAP',
                "gender": 'male',
                "genderswap": 'sadieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sadiegbap',
                "message": '',
                "ageswap": 'sadiegb',
                "gender_age_swap": 'characters_ST/sadie',
            },
        ],
    },

    # Sandra
    {
        "default_character": 'characters_ST/sandra',
        "variants": [
            {
                "name": 'SandraAR',
                "gender": 'female',
                "genderswap": 'sandragbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sandraar',
                "message": '',
                "ageswap": 'characters_ST/sandra',
                "gender_age_swap": 'sandragb',
            },
            {
                "name": 'SandraGB',
                "gender": 'male',
                "genderswap": 'characters_ST/sandra',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sandragb',
                "message": '',
                "ageswap": 'sandragbar',
                "gender_age_swap": 'sandraar',
            },
            {
                "name": 'SandraGBAR',
                "gender": 'male',
                "genderswap": 'sandraar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'sandragbar',
                "message": '',
                "ageswap": 'sandragb',
                "gender_age_swap": 'characters_ST/sandra',
            },
        ],
    },

    # Scarlet
    {
        "default_character": 'characters_ST/scarlet',
        "variants": [
            {
                "name": 'ScarletAR',
                "gender": 'female',
                "genderswap": 'scarletgbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'scarletar',
                "message": '',
                "ageswap": 'characters_ST/scarlet',
                "gender_age_swap": 'scarletgb',
            },
            {
                "name": 'ScarletGB',
                "gender": 'male',
                "genderswap": 'characters_ST/scarlet',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'scarletgb',
                "message": '',
                "ageswap": 'scarletgbar',
                "gender_age_swap": 'scarletar',
            },
            {
                "name": 'ScarletGBAR',
                "gender": 'male',
                "genderswap": 'scarletar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'scarletgbar',
                "message": '',
                "ageswap": 'scarletgb',
                "gender_age_swap": 'characters_ST/scarlet',
            },
        ],
    },

    # Setsuna
    {
        "default_character": 'characters_ST/setsuna',
        "variants": [
            {
                "name": 'SetsunaAP',
                "gender": 'female',
                "genderswap": 'setsunagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'setsunaap',
                "message": '',
                "ageswap": 'characters_ST/setsuna',
                "gender_age_swap": 'setsunagb',
            },
            {
                "name": 'SetsunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/setsuna',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'setsunagb',
                "message": '',
                "ageswap": 'setsunagbap',
                "gender_age_swap": 'characters_ST/setsuna',
            },
            {
                "name": 'SetsunaGBAP',
                "gender": 'male',
                "genderswap": 'setsunaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'setsunagbap',
                "message": '',
                "ageswap": 'setsunagb',
                "gender_age_swap": 'characters_ST/setsuna',
            },
        ],
    },

    # Stevie
    {
        "default_character": 'characters_ST/stevie',
        "variants": [
            {
                "name": 'Stevie',
                "gender": 'male',
                "genderswap": 'steviegb',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'stevie',
                "message": '',
                "ageswap": 'stevieap',
                "gender_age_swap": 'steviegbap',
            },
            {
                "name": 'StevieAP',
                "gender": 'male',
                "genderswap": 'steviegbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'stevieap',
                "message": '',
                "ageswap": 'stevie',
                "gender_age_swap": 'steviegb',
            },
            {
                "name": 'StevieGB',
                "gender": 'female',
                "genderswap": 'stevie',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'steviegb',
                "message": '',
                "ageswap": 'steviegbap',
                "gender_age_swap": 'stevieap',
            },
            {
                "name": 'StevieGBAP',
                "gender": 'female',
                "genderswap": 'stevieap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'steviegbap',
                "message": '',
                "ageswap": 'steviegb',
                "gender_age_swap": 'stevie',
            },
        ],
    },

    # Tori
    {
        "default_character": 'characters_ST/tori',
        "variants": [
            {
                "name": 'ToriAP',
                "gender": 'female',
                "genderswap": 'torigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'toriap',
                "message": '',
                "ageswap": 'characters_ST/tori',
                "gender_age_swap": 'torigb',
            },
            {
                "name": 'ToriGB',
                "gender": 'male',
                "genderswap": 'characters_ST/tori',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'torigb',
                "message": '',
                "ageswap": 'torigbap',
                "gender_age_swap": 'characters_ST/tori',
            },
            {
                "name": 'ToriGBAP',
                "gender": 'male',
                "genderswap": 'toriap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'torigbap',
                "message": '',
                "ageswap": 'torigb',
                "gender_age_swap": 'characters_ST/tori',
            },
        ],
    },

    # Vanessa
    {
        "default_character": 'characters_ST/vanessa',
        "variants": [
            {
                "name": 'VanessaAP',
                "gender": 'female',
                "genderswap": 'vanessagbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'vanessaap',
                "message": '',
                "ageswap": 'characters_ST/vanessa',
                "gender_age_swap": 'vanessagb',
            },
            {
                "name": 'VanessaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/vanessa',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'vanessagb',
                "message": '',
                "ageswap": 'vanessagbap',
                "gender_age_swap": 'characters_ST/vanessa',
            },
            {
                "name": 'VanessaGBAP',
                "gender": 'male',
                "genderswap": 'vanessaap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'vanessagbap',
                "message": '',
                "ageswap": 'vanessagb',
                "gender_age_swap": 'characters_ST/vanessa',
            },
        ],
    },

    # Yui
    {
        "default_character": 'characters_ST/yui',
        "variants": [
            {
                "name": 'YuiAP',
                "gender": 'female',
                "genderswap": 'yuigbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'yuiap',
                "message": '',
                "ageswap": 'characters_ST/yui',
                "gender_age_swap": None,
            },
            {
                "name": 'YuiGBAP',
                "gender": 'male',
                "genderswap": 'yuiap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'yuigbap',
                "message": '',
                "ageswap": None,
                "gender_age_swap": 'characters_ST/yui',
            },
        ],
    },

    # Yuuna
    {
        "default_character": 'characters_ST/yuuna',
        "variants": [
            {
                "name": 'YuunaAR',
                "gender": 'female',
                "genderswap": 'yuunagbar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'yuunaar',
                "message": '',
                "ageswap": 'characters_ST/yuuna',
                "gender_age_swap": 'yuunagb',
            },
            {
                "name": 'YuunaGB',
                "gender": 'male',
                "genderswap": 'characters_ST/yuuna',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'yuunagb',
                "message": '',
                "ageswap": 'yuunagbar',
                "gender_age_swap": 'yuunaar',
            },
            {
                "name": 'YuunaGBAR',
                "gender": 'male',
                "genderswap": 'yuunaar',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'yuunagbar',
                "message": '',
                "ageswap": 'yuunagb',
                "gender_age_swap": 'characters_ST/yuuna',
            },
        ],
    },

    # Zoey
    {
        "default_character": 'characters_ST/zoey',
        "variants": [
            {
                "name": 'ZoeyAP',
                "gender": 'female',
                "genderswap": 'zoeygbap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'zoeyap',
                "message": '',
                "ageswap": 'characters_ST/zoey',
                "gender_age_swap": 'zoeygb',
            },
            {
                "name": 'ZoeyGB',
                "gender": 'male',
                "genderswap": 'characters_ST/zoey',
                "age": 'teen',
                "type": 'human',
                "avatar_path": None,
                "folder": 'zoeygb',
                "message": '',
                "ageswap": 'zoeygbap',
                "gender_age_swap": 'characters_ST/zoey',
            },
            {
                "name": 'ZoeyGBAP',
                "gender": 'male',
                "genderswap": 'zoeyap',
                "age": 'adult',
                "type": 'human',
                "avatar_path": None,
                "folder": 'zoeygbap',
                "message": '',
                "ageswap": 'zoeygb',
                "gender_age_swap": 'characters_ST/zoey',
            },
        ],
    },

]

# Flatten to a single list of 162 dicts for the loader (unchanged API).
TF_CHARACTERS = []
for _block in CHARACTER_BLOCKS:
    _dc = _block["default_character"]
    for _v in _block["variants"]:
        TF_CHARACTERS.append({**_v, "default_character": _dc})


